vector_version: 0.40.0
vector_config_dir: "/etc/vector"
vector_service_dir: "/lib/systemd/system"
vector_config:
  sources:
    logs_file:
      type: file
      include:
        - /home/vector/logs/*.logs
  sinks:
    to_clickhouse:
      type: clickhouse
      inputs:
        - logs_file
      database: sample
      endpoint: http://62.84.114.61:8123
      table: some_log
      auth:
        password: nolar
        user: nolar
      compression: gzip
      skip_unknown_fields: true
